'use client';
// Research and sources — every contribution, its real committed result, the paper
// it implements, and the official dataset used. One honest place to trace claims.
// The "measured" line per card is read live from the committed benchmark artifacts
// (public/research-metrics.json, generated by scripts/gen_results.py).

import { useEffect, useState } from 'react';
import { ExternalLink, FileText, Database, CheckCircle2 } from 'lucide-react';

import AppShell from '../../components/AppShell';
import { RESEARCH, type ResearchItem } from '../../lib/research';
import { cn } from '../../lib/utils';

interface Measured { measured: boolean; value: string; detail: string; }

const TONE: Record<ResearchItem['tone'], { text: string; ring: string; chip: string }> = {
  astra:   { text: 'text-astra-600 dark:text-astra-400',     ring: 'ring-astra-500/20',   chip: 'bg-astra-500/10 text-astra-700 dark:text-astra-300' },
  emerald: { text: 'text-emerald-600 dark:text-emerald-400', ring: 'ring-emerald-500/20', chip: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' },
  rose:    { text: 'text-rose-600 dark:text-rose-400',       ring: 'ring-rose-500/20',     chip: 'bg-rose-500/10 text-rose-700 dark:text-rose-300' },
  purple:  { text: 'text-purple-600 dark:text-purple-400',   ring: 'ring-purple-500/20',   chip: 'bg-purple-500/10 text-purple-700 dark:text-purple-300' },
  amber:   { text: 'text-amber-600 dark:text-amber-400',     ring: 'ring-amber-500/20',    chip: 'bg-amber-500/10 text-amber-700 dark:text-amber-300' },
  sky:     { text: 'text-sky-600 dark:text-sky-400',         ring: 'ring-sky-500/20',      chip: 'bg-sky-500/10 text-sky-700 dark:text-sky-300' },
};

export default function ResearchPage() {
  const [metrics, setMetrics] = useState<Record<string, Measured>>({});
  useEffect(() => {
    fetch('/research-metrics.json')
      .then((r) => (r.ok ? r.json() : {}))
      .then(setMetrics)
      .catch(() => setMetrics({}));
  }, []);

  return (
    <AppShell>
      <div className="mx-auto max-w-6xl px-4 sm:px-6 py-8">
        <header className="mb-8">
          <h1 className="text-2xl font-bold tracking-tight text-ink">Research and sources</h1>
          <p className="mt-2 max-w-3xl text-muted">
            ASTRA-IDE is built on seven contributions. Each one is evaluated on a real public
            dataset, and every headline number below comes from a trained artifact committed in the
            repository. Each card links to the paper it implements and the official dataset, so any
            claim can be traced to its source.
          </p>
        </header>

        <div className="grid gap-4 md:grid-cols-2">
          {RESEARCH.map((r) => {
            const tone = TONE[r.tone];
            const m = metrics[r.id];
            return (
              <article key={r.id} className={cn('card p-5 ring-1', tone.ring)}>
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <span className={cn('inline-block rounded-md px-1.5 py-0.5 text-[11px] font-mono font-semibold', tone.chip)}>
                      {r.id}
                    </span>
                    <h2 className="mt-2 text-lg font-semibold text-ink">{r.name}</h2>
                  </div>
                  <div className="shrink-0 text-right">
                    <div className={cn('text-xl font-bold leading-none', tone.text)}>{r.result}</div>
                  </div>
                </div>

                <p className="mt-2 text-sm text-muted">{r.summary}</p>
                <p className="mt-3 text-sm text-ink/90">{r.resultSub}</p>

                {m?.measured && (
                  <p className="mt-2 inline-flex items-center gap-1.5 rounded-md bg-emerald-500/10 px-2 py-1 text-xs text-emerald-700 dark:text-emerald-300">
                    <CheckCircle2 size={13} className="shrink-0" />
                    <span>Measured: <span className="font-medium">{m.value}</span>{m.detail ? ` (${m.detail})` : ''}</span>
                  </p>
                )}

                <dl className="mt-4 space-y-2 text-sm">
                  <div className="flex gap-2">
                    <dt className="w-16 shrink-0 text-faint">Method</dt>
                    <dd className="text-muted">{r.method}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="w-16 shrink-0 text-faint">Paper</dt>
                    <dd className="text-muted">
                      {r.paperUrl ? (
                        <a href={r.paperUrl} target="_blank" rel="noopener noreferrer"
                           className={cn('inline-flex items-start gap-1 hover:underline', tone.text)}>
                          <FileText size={14} className="mt-0.5 shrink-0" />
                          <span>{r.paper}</span>
                          <ExternalLink size={12} className="mt-0.5 shrink-0 opacity-70" />
                        </a>
                      ) : (
                        <span className="inline-flex items-start gap-1">
                          <FileText size={14} className="mt-0.5 shrink-0 text-faint" />
                          <span>{r.paper}</span>
                        </span>
                      )}
                      <span className="block text-xs text-faint">{r.paperVenue}</span>
                    </dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="w-16 shrink-0 text-faint">Dataset</dt>
                    <dd className="text-muted">
                      {r.datasetUrl ? (
                        <a href={r.datasetUrl} target="_blank" rel="noopener noreferrer"
                           className={cn('inline-flex items-center gap-1 hover:underline', tone.text)}>
                          <Database size={14} className="shrink-0" />
                          <span>{r.dataset}</span>
                          <ExternalLink size={12} className="shrink-0 opacity-70" />
                        </a>
                      ) : (
                        <span className="inline-flex items-center gap-1">
                          <Database size={14} className="shrink-0 text-faint" />
                          <span>{r.dataset}</span>
                        </span>
                      )}
                    </dd>
                  </div>
                </dl>
              </article>
            );
          })}
        </div>

        <p className="mt-8 text-xs text-faint">
          Evaluation harnesses live under <code>benchmarks/</code>; trained artifacts and their
          metrics live under <code>ml/*/artifacts/</code> in the repository.
        </p>
      </div>
    </AppShell>
  );
}
